imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        enabled: false

#doctrine:
#    dbal:
#        dbname:   %test_database_name%
#        user:     %test_database_user%
#        password: %test_database_password%

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
