nothing_flok:
    resource: "@NothingFlokBundle/Resources/config/routing.yml"
    prefix:   /

todo_redirect:
    path:     /todo/
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /
        permanent: true
