services:
    nothing.twig.global_parameters_extension:
        class: Nothing\FlokBundle\Twig\GlobalParametersExtension
        arguments: [@kernel]
        tags:
            - { name: twig.extension }
